#!/usr/bin/env python3
"""
Script to fix LaTeX files generated by Pandoc for ACM format.
This ensures the abstract is placed before \maketitle as required by ACM.
"""

import sys
import re
from pathlib import Path

def fix_acm_tex_file(tex_file_path, abstract_text=None):
    """
    Fix the LaTeX file for ACM format by:
    1. Removing \usepackage{amsmath,amssymb}
    2. Moving the abstract before \maketitle
    
    Args:
        tex_file_path: Path to the .tex file
        abstract_text: Optional abstract text to use if not found in the file
    """
    tex_file = Path(tex_file_path)
    if not tex_file.exists():
        print(f"Error: {tex_file} not found.")
        return False
    
    try:
        with open(tex_file, 'r') as file:
            content = file.read()
        
        # Remove \usepackage{amsmath,amssymb}
        content = re.sub(r'\\usepackage\{amsmath,amssymb\}', '', content)
        
        # Check if we need to move the abstract
        if '\\begin{document}' in content and '\\maketitle' in content:
            # Extract existing abstract if present
            abstract_match = re.search(r'\\begin\{abstract\}(.*?)\\end\{abstract\}', content, re.DOTALL)
            if abstract_match:
                extracted_abstract = abstract_match.group(1).strip()
                # Remove the existing abstract
                content = re.sub(r'\\begin\{abstract\}.*?\\end\{abstract\}', '', content, flags=re.DOTALL)
            else:
                extracted_abstract = abstract_text or "Abstract text goes here."
            
            # Find positions
            begin_doc_pos = content.find('\\begin{document}') + len('\\begin{document}')
            
            # Insert abstract after \begin{document} but before any other content
            new_content = (
                content[:begin_doc_pos] + 
                '\n\n\\begin{abstract}\n' + extracted_abstract + '\n\\end{abstract}\n\n' +
                content[begin_doc_pos:]
            )
            
            # Remove any duplicate abstract that might be after \maketitle
            new_content = re.sub(r'\\maketitle\s*\\begin\{abstract\}.*?\\end\{abstract\}', 
                                '\\maketitle', new_content, flags=re.DOTALL)
            
            content = new_content
        
        # Write the modified content back to the file
        with open(tex_file, 'w') as file:
            file.write(content)
        
        print(f"Successfully fixed {tex_file}")
        return True
    
    except Exception as e:
        print(f"Error fixing LaTeX file: {e}")
        return False

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python fix_tex.py path/to/file.tex [abstract_text]")
        sys.exit(1)
    
    tex_file = sys.argv[1]
    abstract_text = sys.argv[2] if len(sys.argv) > 2 else None
    
    success = fix_acm_tex_file(tex_file, abstract_text)
    sys.exit(0 if success else 1)